apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: node-webapp-build
  labels:
    app: node-app-akhil
  annotations:
    description: Defines a sample node app with no routes
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/NAkhilC/testjenkins.git"
      ref: master
    contextDir: Dockerfile
  strategy:
    type: Docker
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: "node-webapp:latest"
  resources: {}
  successfulBuildHistoryLimit: 5
  failedBuildHistoryLimit: 5
  postCommit: {}
