apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mywebsite
  labels:
    app: mywebsite
spec:
  source:
    type: Git
    git:
      uri: https://github.com/NAkhilC/testjenkins.git
    contextDir: httpd-hello-world
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      from:
        kind: ImageStreamTag # Use an imagestream tag as 'FROM'
        namespace: toms-project # Which project?
        name: httpd:latest # Use the imagestream created above
  output:
    to:
      kind: ImageStreamTag
      name: mywebsite:latest
  triggers:
    - type: ImageChange
