apiVersion: v1
kind: Template
metadata:
  annotations:
    description: build config template
  name: build-config-template
parameters:
  - description: Name of the service to be deployed
    displayName: Service Name
    name: SERVICE_NAME
  - description: Git repository where service is stored
    displayName: GIT Service URL
    name: SERVICE_GIT_URL
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: nothing
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: imagenothing:latest
      source:
        contextDir: /
        git:
          ref: master
          uri: https://github.com/NAkhilC/testjenkins.git
        type: Git
      strategy:
        sourceStrategy:
          env:
            - name: GIT_SSL_NO_VERIFY
              value: "true"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
          from:
            kind: ImageStreamTag
            name: s2i-openshift-alpine-nodejs:latest
            namespace: drya024
        type: Source
