apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nodejs
  labels:
    app: sample-nodejs
spec:
  selector:
    matchLabels:
      app: sample-nodejs
  template:
    metadata:
      labels:
        app: sample-nodejs
    spec:
      containers:
        - image: akhil2715/testnodeapp:latest
          name: nodejs-api
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-nodejs-service
spec:
  ports:
    - name: sample-nodejs-port-service
      targetPort: 3000
      port: 3000
      nodePort: 30243
      protocol: TCP
  selector:
    app: sample-nodejs
  type: NodePort
