apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: testinga1-app-docker
spec:
  lookupPolicy:
    local: false
  imagePullSecrets:
    - name: docker
  tags:
    - name: estinga1-app-docker
      from:
        kind: DockerImage
        name: akhil2715/testnodeapp:latest
      referencePolicy:
        type: Source
