apiVersion: v1
kind: Pod
metadata:
  name: testinga-app-docker
spec:
  containers:
    - name: node-docker-app
      image: index.docker.io/akhil2715/testnodeapp:latest
      imagePullPolicy: Always
      command: ["echo", "SUCCESS"]
  imagePullSecrets:
    - name: myregistrykey
