apiVersion: v1
kind: Pod
metadata:
  name: ngnix-image
spec:
  containers:
 - name: test-deployment1
  image: https://hub.docker.com/r/akhil2715/testnodeapp
  imagePullPolicy: Always
 imagePullSecrets:
 - name: docker